# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
javafaker = "1.0.2"
junit-jupiter = "5.12.2"

[libraries]
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "javafaker" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-launcher = { module = "org.junit.platform:junit-platform-launcher" }
